apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: symlink
  title: Symlink
  description: Example with symlink

spec:
  owner: gdolfen
  type: service
  parameters:
    - title: No Imput needed
  steps:
    - id: fetch
      name: fetch
      action: fetch:template
      input:
        url: ./skeleton
    - id: publish
      name: publish
      action: publish:github:merge-request
      input:
        allowedHosts: ["github.com"]
        repoUrl: https://github.com/gdolfen/backstage_symlink_template
        branchName: 'test'
        title: 'test'
