apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: symlink
  title: Symlink
  description: Example with symlink

spec:
  owner: gdolfen
  type: service
  parameters:
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: fetch
      name: fetch
      action: fetch:template
      input:
        url: ./skeleton
    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        branchName: 'test'
        title: 'test'
